version: "3"

services:
  webserver:
    build: .
    container_name: 'node'
    hostname: node.me
    volumes:
      - ./:/usr/app/
    ports:
      - "3001:3000"
    command: npm run test
    tty: true